name: Deploy on Main Push

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:

    - name: Install gke-gcloud-auth-plugin
      run: |
        curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl plugin install https://github.com/GoogleCloudPlatform/gke-gcloud-auth-plugin/releases/latest/download/gke-gcloud-auth.tar.gz
      
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker europe-west9-docker.pkg.dev

    - name: Get cluster credentials
      run: gcloud container clusters get-credentials my-lab-cluster --zone europe-west9-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Apply namespace
      run: kubectl apply -f namespaces/my-namespace.yaml --validate=false

    - name: Apply backend deployment
      run: kubectl apply -f deployments/backend-deployment.yaml --validate=false

    - name: Apply backend service
      run: kubectl apply -f services/backend-service.yaml --validate=false

    - name: Apply ingress
      run: kubectl apply -f ingress/ingress.yaml --validate=false
